export default {
  Authorization:
    'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9lIEJsb2dncyIsImVtYWlsIjoiam9lLWJsb2dnc0BleGFtcGxlLmNvbSIsIl9pZCI6IjVhNTMyMTM3OTdiNGJlODJkMGVmZjU4NSIsImlhdCI6MTUxNTM5NzQ0Nn0.fnTQmb90Wcf6R9jFZ_ZDpzm2Wp5Af6tsyvToloWOKzA'
}
